rails_site: "http://www.railstutorial.org"
rails_news_site: "http://news.railstutorial.org/"
size: 50
avatar: "https://secure.gravatar.com/avatar/"
number_answer: 4

question:
  types:
    single: "single_choice"
    multiple: "multiple_choices"
    text: "text"
  num_correct: 1
email:
  time: 8.hours.from_now
exam:
  duration: 30
  question_number: 15
  minute: 60
  time_out: 0
  status:
    start: "start"
    testing: "testing"
    uncheck: "uncheck"
    checked: "checked"
filter:
  all: "all"
csv:
  type: .csv
  row: 1
  last_row: 2
